### ISSUE TITLE
npm start returns error and will not build

### ISSUE THREAD

**Issue by brytmill** [ahmadawais/WPGulp#126]
### Expected Behavior

In the theme folder of a fresh WP installation (/wp-content/themes/ulp/), I followed steps 1-3, modifying the wpgulp.config.js line `projectURL: 'localhost/ulp/'` since my site is  accessed locally from http://localhost/ulp/. 

I expected the project to build after `npm start` so I could begin working with WP Gulp

### Actual Behavior

After running `npm start` I receive an error and the project fails to build 
(screenshot https://imgur.com/a/BuIdqr3)

Error log:
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\Bryan\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@6.4.1
3 info using node@v10.12.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle your-project@1.0.0~prestart: your-project@1.0.0
6 info lifecycle your-project@1.0.0~start: your-project@1.0.0
7 verbose lifecycle your-project@1.0.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle your-project@1.0.0~start: PATH: C:\Users\Bryan\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;D:\wamp64\www\ulp\wp-content\themes\ulp\node_modules\.bin;C:\Users\Bryan\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\local\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Users\Bryan\bin;C:\windows\system32;C:\windows;C:\windows\system32\wbem;C:\windows\system32\windowspowershell\v1.0;C:\program files (x86)\windows live\shared;C:\program files (x86)\common files\intuit\qbpossdkruntime;C:\program files (x86)\skype\phone;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0;.;D:\Program Files\Theme Kit\";C:\WINDOWS\System32\OpenSSH;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\Git\cmd;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Program Files\nodejs;C:\RailsInstaller\Git\cmd;C:\RailsInstaller\Ruby1.9.3\bin;C:\Users\Bryan\AppData\Local\Microsoft\WindowsApps;C:\Program Files\Theme Kit;C:\Program Files\watchman;C:\Users\Bryan\AppData\Roaming\npm;C:\Program Files\Git\usr\bin\vendor_perl;C:\Program Files\Git\usr\bin\core_perl
9 verbose lifecycle your-project@1.0.0~start: CWD: D:\wamp64\www\ulp\wp-content\themes\ulp
10 silly lifecycle your-project@1.0.0~start: Args: [ '/d /s /c', 'gulp' ]
11 silly lifecycle your-project@1.0.0~start: Returned: code: 1  signal: null
12 info lifecycle your-project@1.0.0~start: Failed to exec start script
13 verbose stack Error: your-project@1.0.0 start: `gulp`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Users\Bryan\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:182:13)
13 verbose stack     at ChildProcess.<anonymous> (C:\Users\Bryan\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:182:13)
13 verbose stack     at maybeClose (internal/child_process.js:962:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
14 verbose pkgid your-project@1.0.0
15 verbose cwd D:\wamp64\www\ulp\wp-content\themes\ulp
16 verbose Windows_NT 10.0.17134
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Bryan\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "start"
18 verbose node v10.12.0
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 1
22 error your-project@1.0.0 start: `gulp`
22 error Exit status 1
23 error Failed at the your-project@1.0.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

wpgulp.config.js:
```
/**
 * WPGulp Configuration File
 *
 * 1. Edit the variables as per your project requirements.
 * 2. In paths you can add <<glob or array of globs>>.
 *
 * @package WPGulp
 */

module.exports = {

	// Project options.
	projectURL: 'localhost/ulp/', // Local project URL of your already running WordPress site. Could be something like wpgulp.local or localhost:3000 depending upon your local WordPress setup.
	productURL: './', // Theme/Plugin URL. Leave it like it is, since our gulpfile.js lives in the root folder.
	browserAutoOpen: false,
	injectChanges: true,

	// Style options.
	styleSRC: './assets/css/style.scss', // Path to main .scss file.
	styleDestination: './', // Path to place the compiled CSS file. Default set to root folder.
	outputStyle: 'compact', // Available options → 'compact' or 'compressed' or 'nested' or 'expanded'
	errLogToConsole: true,
	precision: 10,

	// JS Vendor options.
	jsVendorSRC: './assets/js/vendor/*.js', // Path to JS vendor folder.
	jsVendorDestination: './assets/js/', // Path to place the compiled JS vendors file.
	jsVendorFile: 'vendor', // Compiled JS vendors file name. Default set to vendors i.e. vendors.js.

	// JS Custom options.
	jsCustomSRC: './assets/js/custom/*.js', // Path to JS custom scripts folder.
	jsCustomDestination: './assets/js/', // Path to place the compiled JS custom scripts file.
	jsCustomFile: 'custom', // Compiled JS custom file name. Default set to custom i.e. custom.js.

	// Images options.
	imgSRC: './assets/img/raw/*', // Source folder of images which should be optimized and watched. You can also specify types e.g. raw/**.{png,jpg,gif} in the glob.
	imgDST: './assets/img/', // Destination folder of optimized images. Must be different from the imagesSRC folder.

	// Watch files paths.
	watchStyles: './assets/css/**/*.scss', // Path to all *.scss files inside css folder and inside them.
	watchJsVendor: './assets/js/vendor/*.js', // Path to all vendor JS files.
	watchJsCustom: './assets/js/custom/*.js', // Path to all custom JS files.
	watchPhp: './**/*.php', // Path to all PHP files.

	// Translation options.
	textDomain: 'WPGULP', // Your textdomain here.
	translationFile: 'WPGULP.pot', // Name of the translation file.
	translationDestination: './languages', // Where to save the translation files.
	packageName: 'WPGULP', // Package name.
	bugReport: 'https://AhmadAwais.com/contact/', // Where can users report bugs.
	lastTranslator: 'Ahmad Awais <your_email@email.com>', // Last translator Email ID.
	team: 'AhmadAwais <your_email@email.com>', // Team's Email ID.

	// Browsers you care about for autoprefixing. Browserlist https://github.com/ai/browserslist
	// The following list is set as per WordPress requirements. Though, Feel free to change.
	BROWSERS_LIST: [
		'last 2 version',
		'> 1%',
		'ie >= 11',
		'last 1 Android versions',
		'last 1 ChromeAndroid versions',
		'last 2 Chrome versions',
		'last 2 Firefox versions',
		'last 2 Safari versions',
		'last 2 iOS versions',
		'last 2 Edge versions',
		'last 2 Opera versions'
	]
};
```

### Steps to Reproduce

0. boot up WAMP and ensure local WP install is live and working
1. open git bash as administrator to live local WP installation > `cd /d/wamp64/www/ulp/wp-content/themes/ulp/`
2. `npx wpgulp`
3. (modified the wpgulp.config.js file 'projectURL' to `projectURL: 'localhost/ulp/'` -- I've also tried other paths, localhost or localhost/ulp)
4. `npm start`

1. `node -v`: v10.12.0
2. `npm -v`: 6.4.1
3. `yarn --version` (if you use Yarn): n/a

Then, specify:

1. Operating system: Windows 10.1
2. Browser and version (if relevant): Chrome Version 69.0.3497.100

**Possible Solution**

1. I started with node v8 (with the same error) and have since upgraded to v10
2. I removed the node_modules folder and tried to rebuild with `npm i`
3. I tried re-running npx wpgulp to rebuild and follow to step 3 again
4. I've ensured that the correct node path is in my environment variables

### Reproducible Demo

(Project is local)

**Comment by ahmadawais** [comment]
It says `node` is not recognized so probably your Node and npm installation is not right or updated enough. I am not on windows so I can't test it.

@saqibameen can you help?

**Comment by brytmill** [comment]
@ahmadawais I've tried both the latest stable version of node for windows v8.12.0 and the latest release v10.12.0 -- neither work.

One thought is that my node is installed on my C drive, and my working WPGulp project is on my D drive. Although, my environment variables are set to the correct path on the C drive so I'm not sure if that has anything to do with it.

Still haven't been able to work it out on my end -- would love to use this on my main PC.

**Comment by ahmadawais** [comment]
This should be fixed in the latest v2.8 of WPGulp. Try it out and let me know by opening this again if it doesn't work

**Comment by brytmill** [comment]
Hi @ahmadawais -- thank you. I've just tried steps 0-4 in the original "steps to reproduce" and I am still receiving the same error.

**Comment by ahmadawais** [comment]
Strange. From reading the error it looks like your node is not being
recognized. Feels more like a Windows + Node issue. I can't reproduce since
I am on mac. Can you try Flywheel Local?
